service: topcoder-scheduler-executor

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 60
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

plugins:
  - serverless-step-functions
  - serverless-bundle

custom:
  bundle:
    linting: false

functions:
  processLambda:
    handler: src/process-lambda.handler
    
stepFunctions:
  stateMachines:
    scheduler:
      name: StateMachine
      definition:
        StartAt: waitX
        States:
          waitX:
            Type: Wait
            TimestampPath: "$.scheduleTime"
            Next: processTask
          processTask:
            Type: Task
            Resource:
              Fn::GetAtt: [processLambda, Arn]
            End: true
  validate: true 
